### ISSUE TITLE
new signatures are added to the first pages in the long list

### ISSUE THREAD

**Issue by rrustema** [petities/petitions.eu#289]
new signatures are added to the first pages of the chronological list of signatures, which totally messes up the list of signatures (not chronological anymore). 

first mentioned by  https://opendomein.nl/cerb5/display/JGQ-27316-945

**Comment by spreeker** [comment]
we decided it to work like that.

**Comment by rrustema** [comment]
did we? why was that? does not make sense, because then it is not a chronological list anymore? 
It is different for old and new petitions. In new petitions it seems to work, but old ones are a mess. 

See for example https://petities.nl/petitions/stop-chemtrails-nu-en-weermanipulatie-nu/signatures?locale=nl&page=1 (they follow closely each extra signature)

**Comment by spreeker** [comment]
Could you give urls which show the issue. I'm confused by what you mean.

**Comment by rrustema** [comment]
first complaint came in about this page https://petities.nl/petitions/stop-chemtrails-nu-en-weermanipulatie-nu/signatures?locale=nl 

The first page is filled with signatures of one month old and newer. At the bottom of the 2nd page it jumps from 'about 3 hours' to 'about 7 years'. From the 2nd to the 190th it counts down chronologically from 'about 7 years' to 'about one month' . https://petities.nl/petitions/stop-chemtrails-nu-en-weermanipulatie-nu/signatures/805407?locale=nl&page=2

Other petitions, older than a month, have similar issues. Sort by biggest is the easiest way to find them https://petities.nl/petitions?locale=nl&sorting=biggest 

New petitions do not have the issue, because their chronological order started later. Their first page contains the oldest page and their last page in the list of signatures has the latest. This error is not easily noticable for most use cases.

**Comment by spreeker** [comment]
it's fixed locally. I will order by first special then confirmed at. I'm now making a checkbox on the petition list which will put special signatures to the top of the list.

**Comment by spreeker** [comment]
fixed! in 84f77135961c9dbe2bd890c2f00ae185dc0aaaf5 , b5e24ee6ab60f580388f43e53e700d5ba89e5285, 5f129fc2e18d8d2bd0a5a05f4c6c8aac137848ba

**Comment by rrustema** [comment]
just noticed that this issue is back

a new petition just got online and receives a lot of signatures. All new signatures are added to the top, pushing the older signatures to the following pages. 

https://petities.nl/petitions/nederland-wil-een-referendum-om-de-eu-te-verlaten/signatures?locale=nl&page=1

https://petities.nl/petitions/nederland-wil-een-referendum-om-de-eu-te-verlaten/signatures?locale=nl&page=2

how can a signatory find his/herself back if the pagenumber changes?

Oldest should be on top (or when the sort order dictates it), newer ones added to the tail. Only in grid view the latest appear (unless overrided by the sort order).

**Comment by rrustema** [comment]
signatories complain. https://opendomein.nl/cerb5/display/HMC-42938-749

The old petition https://petities.nl/petitions/stop-chemtrails-nu-en-weermanipulatie-nu/signatures/ has 190 pages of 100 signatories. The new ones are appearing at page 22. Before page 22 signatures are about 7 years old. The first page has signatures 'over 6 years' old and the 190th page 'about 6 years'. 

Incomprehensible, can't explain/justify this to end users.

**Comment by skoolstra** [comment]
The last comment was more than one year ago and I think this issue was resolved a while back. Ordering of signatures should be consistent on `:special` and `:confirmed_at`. Can you please verify if this issue still exists (and reopen if more attention is required)?
